-- Create orders table IF NOT EXISTS
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_phone text,
  total_amount numeric not null,
  status text default 'Pendente',
  payment_method text,
  delivery_address text,
  notes text
);

-- Create order_items table IF NOT EXISTS
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity int not null,
  unit_price numeric not null,
  product_name text
);

-- Create store_settings table IF NOT EXISTS
create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text default 'Karolayne Doces',
  phone text,
  address text,
  logo_url text,
  opening_hours jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (safe to run multiple times)
alter table orders enable row level security;
alter table order_items enable row level security;
alter table store_settings enable row level security;

-- Policies: DROP first to avoid "already exists" error, then CREATE
drop policy if exists "Enable all access for all users" on orders;
create policy "Enable all access for all users" on orders for all using (true);

drop policy if exists "Enable all access for all users" on order_items;
create policy "Enable all access for all users" on order_items for all using (true);

drop policy if exists "Enable all access for all users" on store_settings;
create policy "Enable all access for all users" on store_settings for all using (true);

-- Insert default settings (only if table is empty)
insert into store_settings (store_name, phone, address)
select 'Karolayne Doces', '(84) 98656-1077', 'Av. Rio Grande do Norte, 402 - Cidade da Esperança'
where not exists (select 1 from store_settings);
