-- =============================================================
-- SCHEMA COMPLETO - Pedilivery / Karolayne Doces
-- Consolidado a partir de: supabase_setup.sql, schema_update_v2.sql,
--   categories_setup.sql, schema_users.sql
-- Execute este arquivo no SQL Editor do Supabase (novo projeto)
-- =============================================================


-- -------------------------------------------------------------
-- 1. USERS
-- -------------------------------------------------------------
create table if not exists public.users (
  id uuid not null default gen_random_uuid(),
  name text not null,
  email text not null,
  password text not null,
  avatar_url text null,
  role text null default 'Cliente'::text,
  created_at timestamp with time zone null default now(),
  constraint usuarios_pkey primary key (id),
  constraint usuarios_email_key unique (email)
) tablespace pg_default;

create index if not exists idx_usuarios_email
  on public.users using btree (email) tablespace pg_default;

create index if not exists idx_usuarios_privilegios
  on public.users using btree (role) tablespace pg_default;

alter table public.users enable row level security;

drop policy if exists "Enable all access for all users" on public.users;
create policy "Enable all access for all users" on public.users for all using (true);


-- -------------------------------------------------------------
-- 2. CATEGORIES
-- -------------------------------------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null,
  icon text,
  order_index integer default 0
);

alter table public.categories enable row level security;

drop policy if exists "Enable read access for all users" on public.categories;
create policy "Enable read access for all users" on public.categories for select using (true);

drop policy if exists "Enable all access for all users" on public.categories;
create policy "Enable all access for all users" on public.categories for all using (true);


-- -------------------------------------------------------------
-- 3. PRODUCTS
-- -------------------------------------------------------------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  detail text,
  category text,
  price numeric,
  stock text default 'Em estoque',
  img text
);

alter table public.products enable row level security;

drop policy if exists "Enable read access for all users" on public.products;
create policy "Enable read access for all users" on public.products for select using (true);

drop policy if exists "Enable all access for all users" on public.products;
create policy "Enable all access for all users" on public.products for all using (true);


-- -------------------------------------------------------------
-- 4. ORDERS
-- -------------------------------------------------------------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_phone text,
  total_amount numeric not null,
  status text default 'Pendente',
  payment_method text,
  delivery_address text,
  notes text
);

alter table public.orders enable row level security;

drop policy if exists "Enable all access for all users" on public.orders;
create policy "Enable all access for all users" on public.orders for all using (true);


-- -------------------------------------------------------------
-- 5. ORDER_ITEMS
-- -------------------------------------------------------------
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity int not null,
  unit_price numeric not null,
  product_name text,
  observation text
);

alter table public.order_items enable row level security;

drop policy if exists "Enable all access for all users" on public.order_items;
create policy "Enable all access for all users" on public.order_items for all using (true);


-- -------------------------------------------------------------
-- 6. STORE_SETTINGS
-- -------------------------------------------------------------
create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text default 'Karolayne Doces',
  phone text,
  address text,
  logo_url text,
  opening_hours jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.store_settings enable row level security;

drop policy if exists "Enable all access for all users" on public.store_settings;
create policy "Enable all access for all users" on public.store_settings for all using (true);


-- =============================================================
-- DADOS DE EXEMPLO
-- =============================================================


-- -------------------------------------------------------------
-- USERS (senhas já com hash bcrypt)
-- -------------------------------------------------------------
insert into public.users (id, name, email, password, avatar_url, role, created_at) values
  ('28e5af05-c231-464a-b90c-964372f3e2ca', 'Nicole Sena',           'nicoles@email.com',      '$2a$10$T1EWKhRbCNJ06YZlSUvWCeM9Oook47c6x58LMUVU9Z8/A13hTQ60K', null, 'Cliente', '2026-04-28 19:50:23.447585+00'),
  ('6f7734e4-0e80-4823-8501-8469fde3060e', 'Jorge Oliveira',        'jorgeo@email.com',       '$2a$10$YNvUbO9lZkUV26C6WI3k/Og6u7ZMCWA.fBCDMS//uYmK0fnlsDGf6', null, 'Cliente', '2026-04-28 19:51:40.262238+00'),
  ('73dddf65-80da-4282-b9b3-9b670268d313', 'Lucia Nascimento',      'lucian@email.com',       '$2a$10$DCli5myNM.DrM07RQAI00O2u6tvYeesst70kS0ad9F3yTYDdByry.', null, 'Cliente', '2026-04-28 19:52:08.464223+00'),
  ('9bcbbbed-d17a-4546-baab-f2557539a782', 'Pedro Quintiliano',     'pedro@email.com',        '$2a$12$lLbexrQ8w/uicYHKn4aEMe75zdDyPaECQxvq6TeKop6jkIPFtms8i', null, 'Cliente', '2026-04-28 03:38:22.19503+00'),
  ('a66f3436-6b4d-42ea-b426-a144b3cf8a2f', 'Valdemir Cordeiro',     'valdemirc@email.com',    '$2a$10$9V5htrt1xDdUDhHv.qYCceNSsMKT7EgWLDWACoULy8V7J60inbND2', null, 'Gestor', '2026-04-28 19:53:00.090558+00'),
  ('a7323fb7-f751-4b6a-9e2f-86a0c289743d', 'Lucas Pereira',         'lucasp@email.com',       '$2a$10$AD3DY5kpm/u8S1ThFbQ6RuPb98tmvw2GWDrZZ0dbNRjXaa.QKsN/S', null, 'Cliente', '2026-04-28 19:48:39.667718+00'),
  ('ab346e62-92a7-4541-bf79-2cb6324b3038', 'Fernando Carvalho',     'fefecarvalho@email.com', '$2a$10$LsDLE7hmbFtX7puZRrnN4e8Q7kywEKoDW6NNXawidonOS7LPhw2be', null, 'Cliente', '2026-04-28 19:49:36.398979+00'),
  ('c0360b4d-3002-4b77-b3ae-bb8dcff8c5d5', 'João Silva',            'joao@email.com',         '$2a$10$GViNigzn9LZbabc0o37pUONfin9Pskk/2tI.4unySWSnT2TL9qrD2', null, 'Cliente', '2026-04-28 19:42:52.075343+00'),
  ('ec0afff6-12a1-4330-a8fc-dd7dd32904ef', 'Maria Eduarda Coelho',  'dudacoelho@email.com',   '$2a$10$dAYmKf.OPgZ94FqP55dU9.87rgkZ62atwSBcrgSLP2RkWG8ScGmsi', null, 'Cliente', '2026-04-28 20:50:21.022919+00'),
  ('ffe04205-b7e9-4e03-ae5b-91c8cd2133a6', 'Beatriz Sobral',        'beatrizs@email.com',     '$2a$10$yVeq97pY6flSKkcap04asu7ndFsu0SR7z4yPuldKIfkvqgfDxf8UG', null, 'Cliente', '2026-04-28 19:49:56.316441+00')
on conflict (id) do nothing;


-- -------------------------------------------------------------
-- CATEGORIES
-- -------------------------------------------------------------
insert into public.categories (name, slug, icon, order_index)
select name, slug, icon, order_index from (values
  ('Vulcões', 'Vulcões', 'Phone', 1),
  ('Bolos',   'Bolos',   'Cake',  2),
  ('Tortas',  'Tortas',  'Cake',  3),
  ('Doces',   'Doces',   'Heart', 4),
  ('Bebidas', 'Bebidas', 'Phone', 5),
  ('Normais', 'Normais', 'Cake',  6)
) as v(name, slug, icon, order_index)
where not exists (select 1 from public.categories limit 1);


-- -------------------------------------------------------------
-- PRODUCTS
-- -------------------------------------------------------------
insert into public.products (name, detail, category, price, stock, img)
select name, detail, category, price, stock, img from (values
  ('Vulcão de Ninho',        'Delicioso bolo vulcão',              'Vulcões', 35.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0T5QiNiWAqPAXwcJYtdAZ_rgkkBum6BEsaTwTX47weFL5_hoNBZi091su2-3fjTtuQWDBMko9bIbQT3c1m2PshfWJ0fxAn5iTiTDcRQ7tSuXKwnHsLe5jnB02PeufYk88WNjgY7-g5LX32wJfW_hIcff1MNqxpGtADFvEjIZiU58Qj24p6r-eJAqToW5ek9FRPlRzjaQDMgc7bWhxqjtnnzfrKa1I1XG04xFl8Yy7TdnL8io60h3uP_pL6WrE-E4YtXhRMZqp14se'),
  ('Vulcão de Nutella',      'Recheio cremoso e intenso',          'Vulcões', 45.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMZIjKlzZv6qdlTMaf5kHJupo4zeeandzjozvipsA2Inq0JeDPe27PQ8Xh1CdeSnIJOHoXhvX9KQ_6qy9sgYdG7O19vBRX8vFNPuc0_Iti1E31xNyvniQSGXEluE7JjbLMMVzC-WxzPgrrGRvb5cK7Z7Anlx-UUCBWDa34QPB2p_fS-MbtfNOs0Ctz4pFe-7eZptXGO9HfJPQ4okSKv-Nd6GXoce6Za5kqs4aM6sgLRAL-z4s89mThh5xn4QKyYfg2qsun2wrQ88C3'),
  ('Vulcão de Cenoura',      'Clássico com cobertura de chocolate','Vulcões', 30.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoLdMkV508uM8rVjG9vZDqSbnjdiB5qKpdC6cj4zFvqrWi-bW5VheePyAB_VQYbVWJ5Tw67MgFlqxulU81y5lgAPFhQG2gi3tRSbSymEAkjbLdnsd47gpTr2kUqfsY4buFLSsteTQ6whu7IGZHMZo67K4kPByJVoOm4XyKPNaeNwnX1fUOutAr6dAGJxezthYwFlwZzin87L25CPO6O513H-cI-rwxO4zRZj7tMqGqO0svMzNnDOgBaLVC3wPgWsztbO3ODTel1I-3'),
  ('Bolo de Milho',          'Sabor do campo',                     'Normais', 15.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2VrlyGcuEer6LT4hWIp77dIaLVoOrTBRxGVUqpoVLZefSdn-fVVTlnbPZtEc97DEqQT_v05k8yrbHB91H6g0gCXrbFL0537ahoV8PcOvh6uaGxaLE84fDmECkOFJV4xN7YBYD3abySy5Mutgq7q56vsaxEw6jZlUjgb454LsvbTc4qIa1gVvHkolKSIp9xdNX9_Ir80JfCfIbL8z589dn4wQu66UrI6_Zv77fqWVDp8OPi7ZgGgYgTzPQLQ5zf-4UCe_n7u6rYPav'),
  ('Bolo de Fubá',           'Tradicional e fofinho',              'Normais', 15.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-dtCPg4etrhDA2d_IL5WOxIaLdbUpkOtf6zTLTvnh5-RjHRi99Bi0VMIPJYee8k-cDXp0uovw4xsS9lLiyLDH0mSzLIFuAYA1cC84QxAZ9fKdRCAgJdyuBlckuDHOTcHYa1bCJ59ODzPDkiJ0LNi23HTWLc-Xus0jwZJ_jZe4v0tdA0QnTszq8aeBmGJBrRnfYhSz5p8BCxniSG3gk9JVNh4NeuXgLEpmuIe-OiaUgVS9ZC3_oTSNXtArOEGB9a5rZG3pbzz8olp-'),
  ('Bolo de Laranja',        'Citrico e refrescante',              'Normais', 18.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmG-ekphOspl3BPSwpR0W6PIGpmrEY0SUBIQtV07ZrrbLRxznaYLS3InlLDGHKPEEE3Vit1-WQc-PlRLn8uvY7A_ziszayptbF2iXQRBs5lHDmzpTgu6NyqSYhmMUAyMbmppPg8NH_unSDuM6j8HbIMvevMeTVWnCXVTnuXYZZRjA9x46Un4y--D5mY7ektqu4kxPIDNBqnJR4dG4A_LnfZnn1dLPJ8l0U8tMpJjLDHLUwwovldW2WT8GmR2x-iZV9Nryb7T1RNg5Z'),
  ('Cupcake de Chocolate',   'Unidade 80g',                        'Doces',   12.50, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuClM5W2KUfjwH9aV1e0HxDmTBWwyiX1TNMpVX633wFL4GCV16bxwk5gWvLuFtySn806OUiYMXMedyQaDKg9wfGZTVhAjC7hXknzpIdzIQ-Gg-fqO9Msj6Nbh0i8Ua80sBQpZrXnUx5hnV889yVplNI7zdPCz8wBpWTG16GwY7kUitHjO5iYzRFuOS9lm1B_uonkLMpUfXPn5WHR-EJqH6m6OwUk9C6-aUDwSQ9CUVLNPoxPq3R9NUaikwrp66GvaEYeSGwMBySb9JF_'),
  ('Bolo de Cenoura G',      'Inteiro - 1.2kg',                    'Bolos',   48.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAfV4BCrum3m-UzsExwDuOepcAL9kX5g8PrQn5KNe57iuDi-9KGuFy7-_YclbRqinioYpmIK6-CUkRSvfDZr031wBvq36fDWYKFynstkFrxXUSYxLPMjkgecltZ00D2uG8VGi4_iSo6kfYuYg3sOYel5pKd5WZHfxL0JVF8SRApiVJCEMdrtumjkDn1fuxb8juU1f6o67F-fyCIyRZfhcaZ3IlvXGQs9jxZmwkZUZtKFyJJRVcLwVTzliUieijMc4HdSaRSKyZM9BA'),
  ('Suco de Laranja 300ml',  'Natural e Fresco',                   'Bebidas',  9.00, 'Esgotado',   'https://lh3.googleusercontent.com/aida-public/AB6AXuBnDPPo4mTLXpLbxOuKXooUzutWS9dCpn9w9KFu1qFH4RJPJU59kdsY1RFcFM_A5pg9S6ClrmHicXWEja6jcPysVBhic5l_xZOu1Zk6q50NrNqnLqPSClXIqHFuYUEXz5pqPZw2DXGwaqwUQEfwGjilCdnfA3LuPFgpCiV87NmfbDa3TwgKBgS_Zj0SS0U1ox8a3rA8u-ne0LW-N3UaOzWYsMKisisTOHL5XwZtxhchecgNYDvwddlugViaeOuPZcx76Zy-0T-urluC'),
  ('Fatia de Torta Holandesa','Cremosa e crocante',                'Tortas',  15.90, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0k7EdOTAIV_zdGuAQle6-VAHIT1EaOm_cogg83DcpMN45_1f8qxP-aRNnIuQr7lLYzhhLF7oUO9DZUmeQJm4jziDocQW7r2V4JwmWYjCNYQYP2pmtXzsyopVzKMgl0hFvZQLQ-XOqIZd1X2X1DVw385uj_0l511dVTQR6xheXYg3jUhk5JBVIY1qYtLuxq6JLxeFrkZVAn-hKGlUoMWk2AbqfWn0mHWpBmKk69yvIs5XC3RCDelsP7zxm3bo7teRIYV8JdUQi0rYH')
) as v(name, detail, category, price, stock, img)
where not exists (select 1 from public.products limit 1);


-- -------------------------------------------------------------
-- STORE_SETTINGS
-- -------------------------------------------------------------
insert into public.store_settings (store_name, phone, address)
select 'Karolayne Doces', '(84) 98656-1077', 'Av. Rio Grande do Norte, 402 - Cidade da Esperança'
where not exists (select 1 from public.store_settings);
