-- Create the products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  detail text,
  category text,
  price numeric,
  stock text default 'Em estoque',
  img text
);

-- Turn on Row Level Security
alter table products enable row level security;

-- Create policy to allow read access to everyone
create policy "Enable read access for all users" on products for select using (true);

-- Create policy to allow insert/update/delete for everyone (since we are not doing auth yet, using public key for now - user requested to make it work)
-- Note: In a real production app with auth, you'd restrict this to authenticated users.
create policy "Enable all access for all users" on products for all using (true);

-- Insert initial data from ClientHome (Landing Page)
insert into products (name, detail, category, price, stock, img) values
('Vulcão de Ninho', 'Delicioso bolo vulcão', 'Vulcões', 35.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0T5QiNiWAqPAXwcJYtdAZ_rgkkBum6BEsaTwTX47weFL5_hoNBZi091su2-3fjTtuQWDBMko9bIbQT3c1m2PshfWJ0fxAn5iTiTDcRQ7tSuXKwnHsLe5jnB02PeufYk88WNjgY7-g5LX32wJfW_hIcff1MNqxpGtADFvEjIZiU58Qj24p6r-eJAqToW5ek9FRPlRzjaQDMgc7bWhxqjtnnzfrKa1I1XG04xFl8Yy7TdnL8io60h3uP_pL6WrE-E4YtXhRMZqp14se'),
('Vulcão de Nutella', 'Recheio cremoso e intenso', 'Vulcões', 45.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMZIjKlzZv6qdlTMaf5kHJupo4zeeandzjozvipsA2Inq0JeDPe27PQ8Xh1CdeSnIJOHoXhvX9KQ_6qy9sgYdG7O19vBRX8vFNPuc0_Iti1E31xNyvniQSGXEluE7JjbLMMVzC-WxzPgrrGRvb5cK7Z7Anlx-UUCBWDa34QPB2p_fS-MbtfNOs0Ctz4pFe-7eZptXGO9HfJPQ4okSKv-Nd6GXoce6Za5kqs4aM6sgLRAL-z4s89mThh5xn4QKyYfg2qsun2wrQ88C3'),
('Vulcão de Cenoura', 'Clássico com cobertura de chocolate', 'Vulcões', 30.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoLdMkV508uM8rVjG9vZDqSbnjdiB5qKpdC6cj4zFvqrWi-bW5VheePyAB_VQYbVWJ5Tw67MgFlqxulU81y5lgAPFhQG2gi3tRSbSymEAkjbLdnsd47gpTr2kUqfsY4buFLSsteTQ6whu7IGZHMZo67K4kPByJVoOm4XyKPNaeNwnX1fUOutAr6dAGJxezthYwFlwZzin87L25CPO6O513H-cI-rwxO4zRZj7tMqGqO0svMzNnDOgBaLVC3wPgWsztbO3ODTel1I-3'),
('Bolo de Milho', 'Sabor do campo', 'Normais', 15.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2VrlyGcuEer6LT4hWIp77dIaLVoOrTBRxGVUqpoVLZefSdn-fVVTlnbPZtEc97DEqQT_v05k8yrbHB91H6g0gCXrbFL0537ahoV8PcOvh6uaGxaLE84fDmECkOFJV4xN7YBYD3abySy5Mutgq7q56vsaxEw6jZlUjgb454LsvbTc4qIa1gVvHkolKSIp9xdNX9_Ir80JfCfIbL8z589dn4wQu66UrI6_Zv77fqWVDp8OPi7ZgGgYgTzPQLQ5zf-4UCe_n7u6rYPav'),
('Bolo de Fubá', 'Tradicional e fofinho', 'Normais', 15.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-dtCPg4etrhDA2d_IL5WOxIaLdbUpkOtf6zTLTvnh5-RjHRi99Bi0VMIPJYee8k-cDXp0uovw4xsS9lLiyLDH0mSzLIFuAYA1cC84QxAZ9fKdRCAgJdyuBlckuDHOTcHYa1bCJ59ODzPDkiJ0LNi23HTWLc-Xus0jwZJ_jZe4v0tdA0QnTszq8aeBmGJBrRnfYhSz5p8BCxniSG3gk9JVNh4NeuXgLEpmuIe-OiaUgVS9ZC3_oTSNXtArOEGB9a5rZG3pbzz8olp-'),
('Bolo de Laranja', 'Citrico e refrescante', 'Normais', 18.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmG-ekphOspl3BPSwpR0W6PIGpmrEY0SUBIQtV07ZrrbLRxznaYLS3InlLDGHKPEEE3Vit1-WQc-PlRLn8uvY7A_ziszayptbF2iXQRBs5lHDmzpTgu6NyqSYhmMUAyMbmppPg8NH_unSDuM6j8HbIMvevMeTVWnCXVTnuXYZZRjA9x46Un4y--D5mY7ektqu4kxPIDNBqnJR4dG4A_LnfZnn1dLPJ8l0U8tMpJjLDHLUwwovldW2WT8GmR2x-iZV9Nryb7T1RNg5Z');

-- Insert initial data from AdminCatalog (that were distinct)
insert into products (name, detail, category, price, stock, img) values
('Cupcake de Chocolate', 'Unidade 80g', 'Doces', 12.50, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuClM5W2KUfjwH9aV1e0HxDmTBWwyiX1TNMpVX633wFL4GCV16bxwk5gWvLuFtySn806OUiYMXMedyQaDKg9wfGZTVhAjC7hXknzpIdzIQ-Gg-fqO9Msj6Nbh0i8Ua80sBQpZrXnUx5hnV889yVplNI7zdPCz8wBpWTG16GwY7kUitHjO5iYzRFuOS9lm1B_uonkLMpUfXPn5WHR-EJqH6m6OwUk9C6-aUDwSQ9CUVLNPoxPq3R9NUaikwrp66GvaEYeSGwMBySb9JF_'),
('Bolo de Cenoura G', 'Inteiro - 1.2kg', 'Bolos', 48.00, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAfV4BCrum3m-UzsExwDuOepcAL9kX5g8PrQn5KNe57iuDi-9KGuFy7-_YclbRqinioYpmIK6-CUkRSvfDZr031wBvq36fDWYKFynstkFrxXUSYxLPMjkgecltZ00D2uG8VGi4_iSo6kfYuYg3sOYel5pKd5WZHfxL0JVF8SRApiVJCEMdrtumjkDn1fuxb8juU1f6o67F-fyCIyRZfhcaZ3IlvXGQs9jxZmwkZUZtKFyJJRVcLwVTzliUieijMc4HdSaRSKyZM9BA'),
('Suco de Laranja 300ml', 'Natural e Fresco', 'Bebidas', 9.00, 'Esgotado', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnDPPo4mTLXpLbxOuKXooUzutWS9dCpn9w9KFu1qFH4RJPJU59kdsY1RFcFM_A5pg9S6ClrmHicXWEja6jcPysVBhic5l_xZOu1Zk6q50NrNqnLqPSClXIqHFuYUEXz5pqPZw2DXGwaqwUQEfwGjilCdnfA3LuPFgpCiV87NmfbDa3TwgKBgS_Zj0SS0U1ox8a3rA8u-ne0LW-N3UaOzWYsMKisisTOHL5XwZtxhchecgNYDvwddlugViaeOuPZcx76Zy-0T-urluC'),
('Fatia de Torta Holandesa', 'Cremosa e crocante', 'Tortas', 15.90, 'Em estoque', 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0k7EdOTAIV_zdGuAQle6-VAHIT1EaOm_cogg83DcpMN45_1f8qxP-aRNnIuQr7lLYzhhLF7oUO9DZUmeQJm4jziDocQW7r2V4JwmWYjCNYQYP2pmtXzsyopVzKMgl0hFvZQLQ-XOqIZd1X2X1DVw385uj_0l511dVTQR6xheXYg3jUhk5JBVIY1qYtLuxq6JLxeFrkZVAn-hKGlUoMWk2AbqfWn0mHWpBmKk69yvIs5XC3RCDelsP7zxm3bo7teRIYV8JdUQi0rYH');
