-- Create categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null, -- Display name (e.g. 'Bolos Vulcões')
  slug text not null, -- Internal ID (e.g. 'Vulcões') matching product category
  icon text, -- Icon name (optional)
  order_index integer default 0
);

-- Enable RLS
alter table categories enable row level security;

-- Policies
create policy "Enable read access for all users" on categories for select using (true);
create policy "Enable all access for all users" on categories for all using (true);

-- Insert initial categories
insert into categories (name, slug, icon, order_index) values
('Vulcões', 'Vulcões', 'Phone', 1),
('Bolos', 'Bolos', 'Cake', 2),
('Tortas', 'Tortas', 'Cake', 3),
('Doces', 'Doces', 'Heart', 4),
('Bebidas', 'Bebidas', 'Phone', 5),
('Normais', 'Normais', 'Cake', 6);
